# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9f8b90b1f35ac4c00b607532517eaddae7c4efe711a83cc1ac4e46a7c6578e0fa88d6d1c81f7ad0dba372afe3690ab23acff0053f8431d5d1b5202c4d179d326

test:
  secret_key_base: 6db1ebe775b4daadd4db663663e433742e641a7a3382aa0598d45809634109dfa3fb2e9149964bb05d489874886847fb5df9eb1073c576ebd82c9e702a93ce2c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
